name: User Information
description: Template for collecting user information
title: "[USER]: "
labels:
  - user-info
body:
  - type: markdown
    attributes:
      value: |
        ## User Information Form
        Please provide your details below.
  - type: input
    id: name
    attributes:
      label: Your Name
      description: Please enter your full name
      placeholder: John Doe
    validations:
      required: true
  - type: input
    id: position
    attributes:
      label: Your Position
      description: Please enter your current position or role
      placeholder: Software Developer
    validations:
      required: true