name: Parse Issue Information

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'user-info')
    permissions:
      issues: write
    steps:
      - name: Debug Issue Body
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body:"
          echo "${{ github.event.issue.body }}"
      
      - name: Parse issue body
        id: parse
        run: |
          # Save issue body to a file for easier processing
          echo '${{ github.event.issue.body }}' > issue_body.txt
          
          # Extract name using grep with better pattern matching
          NAME=$(grep -A 2 "### Your Name" issue_body.txt | tail -n 1 | xargs)
          echo "Extracted Name: $NAME"
          echo "NAME=$NAME" >> $GITHUB_OUTPUT
          
          # Extract position using grep with better pattern matching
          POSITION=$(grep -A 2 "### Your Position" issue_body.txt | tail -n 1 | xargs)
          echo "Extracted Position: $POSITION" 
          echo "POSITION=$POSITION" >> $GITHUB_OUTPUT
      
      - name: Output parsed information
        run: |
          echo "Parsed information from issue:"
          echo "Name: ${{ steps.parse.outputs.NAME }}"
          echo "Position: ${{ steps.parse.outputs.POSITION }}"
      
      - name: Add comment to issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const name = '${{ steps.parse.outputs.NAME }}';
            const position = '${{ steps.parse.outputs.POSITION }}';
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## Parsed Information
              
              **Name:** ${name}
              **Position:** ${position}
              
              Thank you for your submission!`
            });