name: Parse Issue Information

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'user-info')
    permissions:
      issues: write
    steps:
      - name: Debug Issue Body
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body:"
          echo "${{ github.event.issue.body }}"
      
      - name: Parse issue body
        id: parse
        run: |
          ISSUE_BODY='${{ toJSON(github.event.issue.body) }}'
          echo "Full issue body: $ISSUE_BODY"
          
          # Extract name using grep (more reliable than sed in this context)
          NAME=$(echo '${{ github.event.issue.body }}' | grep -A 1 "### Your Name" | tail -n 1 | xargs)
          echo "NAME=$NAME" >> $GITHUB_OUTPUT
          echo "Extracted Name: $NAME"
          
          # Extract position using grep
          POSITION=$(echo '${{ github.event.issue.body }}' | grep -A 1 "### Your Position" | tail -n 1 | xargs)
          echo "POSITION=$POSITION" >> $GITHUB_OUTPUT
          echo "Extracted Position: $POSITION"
      
      - name: Output parsed information
        run: |
          echo "Parsed information from issue:"
          echo "Name: ${{ steps.parse.outputs.NAME }}"
          echo "Position: ${{ steps.parse.outputs.POSITION }}"
      
      - name: Add comment to issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const name = '${{ steps.parse.outputs.NAME }}';
            const position = '${{ steps.parse.outputs.POSITION }}';
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## Parsed Information
              
              **Name:** ${name}
              **Position:** ${position}
              
              Thank you for your submission!`
            });