name: Parse Issue Information

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'user-info')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Parse issue body
        id: parse
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "Issue Body: $ISSUE_BODY"
          
          # Extract name from issue body
          NAME=$(echo "$ISSUE_BODY" | sed -n '/### Your Name/{n;n;p}' | xargs)
          echo "Extracted Name: $NAME"
          echo "NAME=$NAME" >> $GITHUB_ENV
          
          # Extract position from issue body
          POSITION=$(echo "$ISSUE_BODY" | sed -n '/### Your Position/{n;n;p}' | xargs)
          echo "Extracted Position: $POSITION"
          echo "POSITION=$POSITION" >> $GITHUB_ENV
          
      - name: Output parsed information
        run: |
          echo "Parsed information from issue:"
          echo "Name: ${{ env.NAME }}"
          echo "Position: ${{ env.POSITION }}"
          
      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## Parsed Information
            
            **Name:** ${{ env.NAME }}
            **Position:** ${{ env.POSITION }}
            
            Thank you for your submission!